version: '3'
services:
  datasource:
    image: poc/datasource
    ports:
      - 8080:8080
    networks:
      - datasource-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    ports:
      - 3306:3306
    networks:
      - datasource-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb


networks:
  datasource-mysql: